# -*- coding: utf-8 -*-
"""Untitled3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16mv4l690rfO1VsYyXT7hzmT_T5hya3V1
"""

## ASSIGNMENT 3

# =========================
# Imports
# =========================

import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from math import sqrt

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, GRU, Dense


# =========================
# Helper functions
# =========================

def load_series(csv_path):
    """
    Load historical demand from CSV and return as 1D numpy array.
    Uses the 'Demand' column from historical_demand.csv.
    """
    df = pd.read_csv(csv_path)
    series = df["Demand"].values.astype(float)
    return series


def train_val_split(series, train_ratio=0.8):
    """
    Time-based split of the series into train and validation.
    """
    n = len(series)
    train_size = int(n * train_ratio)
    train = series[:train_size]
    val = series[train_size:]
    return train, val


def scale_data(train, val):
    """
    Fit MinMaxScaler on train, transform train and val.
    Returns: scaler, train_scaled, val_scaled
    """
    scaler = MinMaxScaler(feature_range=(0.0, 1.0))

    train = train.reshape(-1, 1)
    val = val.reshape(-1, 1)

    scaler.fit(train)
    train_scaled = scaler.transform(train)
    val_scaled = scaler.transform(val)

    return scaler, train_scaled, val_scaled


def create_sequences(data, lookback=7):
    """
    Convert a scaled 1D series into supervised sequences for RNN.

    Inputs: last 7 days [s_{t-6}, ..., s_t]
    Target: s_{t+1}
    """
    X, y = [], []

    # data shape: (n, 1)
    # i indexes the "current" day t
    # we want data[i-lookback : i+1] as inputs and data[i+1] as target
    for i in range(lookback, len(data) - 1):
        window = data[i - lookback:i + 1]      # shape (lookback+1, 1) = (7, 1)
        X.append(window)
        y.append(data[i + 1, 0])

    X = np.array(X)
    y = np.array(y)
    return X, y


def build_lstm_model(input_shape):
    """
    Simple LSTM model: one LSTM layer + Dense(1).
    """
    model = Sequential()
    model.add(LSTM(32, input_shape=input_shape))
    model.add(Dense(1))
    model.compile(optimizer="adam", loss="mse")
    return model


def build_gru_model(input_shape):
    """
    Simple GRU model: one GRU layer + Dense(1).
    """
    model = Sequential()
    model.add(GRU(32, input_shape=input_shape))
    model.add(Dense(1))
    model.compile(optimizer="adam", loss="mse")
    return model


def naive_forecast(series):
    """
    Naive forecast: D_hat[t+1] = s[t]
    Returns (preds, actuals) over the series.
    """
    preds = series[:-1]
    actuals = series[1:]
    return preds, actuals


def moving_average_forecast(series, window=7):
    """
    7-day moving average forecast:
    D_hat[t+1] = mean(s[t], ..., s[t-6])
    """
    preds = []
    actuals = []

    for i in range(window, len(series)):
        window_vals = series[i - window:i]
        preds.append(np.mean(window_vals))
        actuals.append(series[i])

    return np.array(preds), np.array(actuals)


def rmse(y_true, y_pred):
    return sqrt(mean_squared_error(y_true, y_pred))


def total_inventory_cost(y_true, y_pred, cholding=1.0, cstockout=5.0):
    """
    Compute Total Inventory Cost over a period.

    Ct = cholding * max(0, D_hat_t - s_t) + cstockout * max(0, s_t - D_hat_t)
    Ctot = sum_t Ct
    """
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)

    excess = np.maximum(0.0, y_pred - y_true)
    shortage = np.maximum(0.0, y_true - y_pred)

    daily_cost = cholding * excess + cstockout * shortage
    return float(np.sum(daily_cost))

# =========================
# Main script
# =========================

def main():
    # 1. Load series from historical_demand.csv
    series = load_series("historical_demand.csv")

    # 2. Train/validation split (time-based)
    train, val = train_val_split(series, train_ratio=0.8)

    # 3. Scale data using Min-Max (fit on train only)
    scaler, train_scaled, val_scaled = scale_data(train, val)

    lookback = 7

    # 4. Create supervised sequences for train and validation
    X_train, y_train = create_sequences(train_scaled, lookback=lookback)
    X_val, y_val = create_sequences(val_scaled, lookback=lookback)

    # Input shape for LSTM/GRU: (timesteps, features)
    timesteps = X_train.shape[1]
    n_features = X_train.shape[2]
    input_shape = (timesteps, n_features)

    # 5. Build LSTM and GRU models
    lstm_model = build_lstm_model(input_shape)
    gru_model = build_gru_model(input_shape)

    # 6. Train models
    lstm_model.fit(
        X_train,
        y_train,
        epochs=20,
        batch_size=16,
        verbose=0,
        validation_data=(X_val, y_val)
    )

    gru_model.fit(
        X_train,
        y_train,
        epochs=20,
        batch_size=16,
        verbose=0,
        validation_data=(X_val, y_val)
    )

    # 7. Evaluate models on validation (in ORIGINAL units)

    # Predict (still in scaled space)
    lstm_val_pred_scaled = lstm_model.predict(X_val, verbose=0)
    gru_val_pred_scaled = gru_model.predict(X_val, verbose=0)

    # y_val is scaled; reshape for inverse transform
    y_val_scaled = y_val.reshape(-1, 1)

    # Inverse transform to original demand units
    lstm_val_pred = scaler.inverse_transform(lstm_val_pred_scaled).flatten()
    gru_val_pred = scaler.inverse_transform(gru_val_pred_scaled).flatten()
    y_val_original = scaler.inverse_transform(y_val_scaled).flatten()

    lstm_rmse = rmse(y_val_original, lstm_val_pred)
    gru_rmse = rmse(y_val_original, gru_val_pred)

    # 8. Model selection based on RMSE (validation)
    if gru_rmse < lstm_rmse:
        best_name = "GRU Model"
        best_rmse = gru_rmse
        best_pred = gru_val_pred
    else:
        best_name = "LSTM Model"
        best_rmse = lstm_rmse
        best_pred = lstm_val_pred

    # 9. Baseline forecasts on the validation segment
    # We need baselines on the same days as y_val_original.

    # For the validation segment:
    # y_val_original corresponds to later days in 'val'.
    n_val_points = len(y_val_original)

    # Naive baseline on full validation series
    naive_pred_full, naive_actual_full = naive_forecast(val)
    # Align last n_val_points to match y_val_original
    naive_pred = naive_pred_full[-n_val_points:]
    naive_actual = naive_actual_full[-n_val_points:]

    # 7-day moving average baseline
    ma_pred_full, ma_actual_full = moving_average_forecast(val, window=7)
    ma_pred = ma_pred_full[-n_val_points:]
    ma_actual = ma_actual_full[-n_val_points:]

    # 10. Compute RMSE for baselines
    naive_rmse = rmse(naive_actual, naive_pred)
    ma_rmse = rmse(ma_actual, ma_pred)

    # 11. Compute Total Inventory Cost for all three
    model_c_tot = total_inventory_cost(y_val_original, best_pred)
    naive_c_tot = total_inventory_cost(naive_actual, naive_pred)
    ma_c_tot = total_inventory_cost(ma_actual, ma_pred)

    # 12. Prepare results for cleaner output using pandas DataFrame
    results = [
        {"Forecast": best_name, "RMSE": best_rmse, "Ctot": model_c_tot},
        {"Forecast": "Naive", "RMSE": naive_rmse, "Ctot": naive_c_tot},
        {"Forecast": "MA", "RMSE": ma_rmse, "Ctot": ma_c_tot}
    ]
    results_df = pd.DataFrame(results)

    # 13. Print results as a table to stdout
    print("\n--- Forecasting Results ---")
    display(results_df.round(4))


if __name__ == "__main__":
    main()